Repository algorand/py-algorand-sdk, pull requests merged in 2022-08, with the labels that each got.

#360 Testing: Modify cucumber steps to use dev mode network
  Makefile
  tests/steps/account_v2_steps.py
  tests/steps/application_v2_steps.py
  tests/steps/other_v2_steps.py
  tests/steps/steps.py
Labels: Enhancement

#368 bug-fix: add check to desc so we dont output null if undefined
  algosdk/abi/contract.py
Labels: Bug-Fix

#369 FOR REVIEW ONLY - py-algorand-sdk v1.16.1
  CHANGELOG.md
  Makefile
  algosdk/abi/contract.py
  algosdk/logic.py
  setup.py
  tests/steps/account_v2_steps.py
  tests/steps/application_v2_steps.py
  tests/steps/other_v2_steps.py
  tests/steps/steps.py
  tests/unit_tests/test_other.py
Labels: Skip-Release-Notes

#367 Enhancement: Trim the indexer images and use the sandbox instead of custom dockers
  .test-env
  Dockerfile
  Makefile
  run_integration.sh
  test-harness.sh
  tests/integration.tags
  tests/steps/account_v2_steps.py
  tests/steps/application_v2_steps.py
  tests/steps/other_v2_steps.py
  tests/steps/steps.py
  tests/unit.tags
Labels: Enhancement

#373 Bug-fix: Pass verbosity through to testing harness
  README.md
  test-harness.sh
Labels: Bug-Fix

#370 Enhancement: Add State Proof support
  algosdk/constants.py
  algosdk/future/transaction.py
  algosdk/v2client/algod.py
  tests/steps/other_v2_steps.py
  tests/steps/steps.py
  tests/unit.tags
  tests/unit_tests/test_other.py
Labels: Enhancement

#371 Enhancement: Deprecating use of langspec
  algosdk/future/transaction.py
  algosdk/logic.py
  algosdk/testing/dryrun.py
  algosdk/transaction.py
  tests/steps/steps.py
  tests/unit.tags
Labels: Enhancement

#378 Mergeback: Release v1.17.0b1
  CHANGELOG.md
  README.md
  setup.py
Labels: Skip-Release-Notes
