Repository algorand/py-algorand-sdk, pull requests merged in 2022-11, with the labels that each got.

#348 Boxes: Add support for Boxes
  CHANGELOG.md
  algosdk/atomic_transaction_composer.py
  algosdk/box_reference.py
  algosdk/encoding.py
  algosdk/error.py
  algosdk/future/transaction.py
  algosdk/v2client/algod.py
  algosdk/v2client/indexer.py
  tests/integration.tags
  tests/steps/application_v2_steps.py
  tests/steps/other_v2_steps.py
  tests/steps/steps.py
  tests/unit.tags
  tests/unit_tests/test_other.py
  tests/unit_tests/test_transaction.py
Labels: New Feature

#394 FOR REVIEW ONLY: py-algorand-sdk v1.20.0
  CHANGELOG.md
  algosdk/atomic_transaction_composer.py
  algosdk/box_reference.py
  algosdk/encoding.py
  algosdk/error.py
  algosdk/future/transaction.py
  algosdk/v2client/algod.py
  algosdk/v2client/indexer.py
  setup.py
  tests/integration.tags
  tests/steps/application_v2_steps.py
  tests/steps/other_v2_steps.py
  tests/steps/steps.py
  tests/unit.tags
  tests/unit_tests/test_other.py
  tests/unit_tests/test_transaction.py
Labels: Skip-Release-Notes

#396 Bug-fix: Implement `TransactionRejectedError`
  algosdk/error.py
Labels: Bug-Fix

#398 Decoding: Fix roundtrip encode/decode tests for transactions
  algosdk/box_reference.py
  algosdk/future/transaction.py
Labels: Bug-Fix

#399 FOR REVIEW ONLY: py-algorand-sdk v1.20.1
  CHANGELOG.md
  algosdk/box_reference.py
  algosdk/error.py
  algosdk/future/transaction.py
  setup.py
Labels: Team Hyper Flow

#400 Tests: Migrate v1 algod dependencies to v2 in cucumber tests
  tests/steps/application_v2_steps.py
  tests/steps/other_v2_steps.py
  tests/steps/steps.py
Labels: Enhancement

#401 Enhancement: allowing zero length static array
  algosdk/abi/array_static_type.py
  algosdk/abi/base_type.py
  tests/unit_tests/test_abi.py
Labels: Enhancement

#402 Bug-Fix: encode ABI string with non-ASCII characters
  algosdk/abi/string_type.py
  tests/unit_tests/test_abi.py
Labels: Bug-Fix
