Repository algorand/py-algorand-sdk, pull requests merged in 2023-08, with the labels that each got.

#508 bug-fix: include currency-greater-than param for 0 value
  .test-env
  algosdk/v2client/indexer.py
Labels: Team Lamprey, Bug-Fix

#505 Simulation: Execution trace (PC/Stack/Scratch) support
  algosdk/atomic_transaction_composer.py
  algosdk/v2client/models/__init__.py
  algosdk/v2client/models/simulate_request.py
  tests/integration.tags
  tests/steps/other_v2_steps.py
Labels: New Feature

#510 Text: Fix pre-release-version description in create-release-pr workflow
  .github/workflows/create-release-pr.yml
Labels: Team Hyper Flow, Skip-Release-Notes
