Repository algorand/py-algorand-sdk, pull requests merged in 2023-05, with the labels that each got.

#473 DevOps: Add CODEOWNERS to restrict workflow editing
  .github/workflows/pr-type-category.yml
  CODEOWNERS
Labels: Enhancement

#476 bugfix: incorrect indexer docs
  algosdk/v2client/indexer.py
  docs/algosdk/index.rst
Labels: Bug-Fix

#478 tweak: reorder GenericSignedTransaction type alias
  algosdk/transaction.py
Labels: Enhancement, Team Lamprey

#481 Enhancement: Adding `box_reference.py` to Read The Docs
  docs/algosdk/box_reference.rst
  docs/algosdk/index.rst
  docs/conf.py
Labels: Enhancement

#484 Algod: Simulation run with extra budget per transaction group
  algosdk/atomic_transaction_composer.py
  algosdk/v2client/models/simulate_request.py
  tests/integration.tags
  tests/steps/other_v2_steps.py
Labels: New Feature

#483 algod: State delta endpoints
  algosdk/v2client/algod.py
  tests/steps/other_v2_steps.py
  tests/unit.tags
Labels: Enhancement

#487 Docs: update README to include pointer to the testing repo
  README.md
Labels: Skip-Release-Notes

#486 Enhancement: verbose harness
  .test-env
Labels: Skip-Release-Notes

#488 community: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Skip-Release-Notes
