Repository algorand/py-algorand-sdk, pull requests merged in 2024-06, with the labels that each got.

#539 Tests: Enable min-balance Cucumber tests.
  tests/unit.tags
Labels: Enhancement

#529 algod: Even in the face of urllib.error.HTTPError, return the json
  algosdk/error.py
  algosdk/v2client/algod.py
  examples/inspect-error.py
  examples/utils.py
Labels: Bug-Fix

#544 Tests: Update .test-env to use Cucumber specs from master
  .test-env
Labels: Skip-Release-Notes

#545 Fix: Pass args to underlying `kmd_request` function, including timeout
  algosdk/kmd.py
Labels: Bug-Fix
